#!/bin/sh
# https://unix.stackexchange.com/a/24030
dir1=.
while inotifywait -qqre "attrib,modify,close_write,move,move_self,create,delete,delete_self" "$dir1"; do
    hatch run scribo --build docs
done
